version: "3"
services:
  redis:
    image: redis:6.2-alpine
    restart: always
 
  server:
    build: ./server
    env_file: server.env
    # ports:
    #   - 3333
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 4

  web:
    build: ./web
    depends_on:
      - redis
      - server
    deploy:
      mode: replicated
      replicas: 1
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 804:80
    depends_on:
      - redis
      - server
      - web

       
